sudo: false
language: go
go:
  - 1.9
env: PATH=/home/travis/gopath/bin:$PATH
script:
  - make test
  - make lint
  - make cross
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: El/qxSDFFxk0KCI4e7ed6Jyau6Lw4u8h9CejN1ke2WHez6Nyv9f41uEM+EQFxp/mfdVEAlkjAA/A+nknWP9gJeANqhCpmEaFQ5J3eaW2nECd8fglclqdVP9NZ7Fbl4qTKsQpD7xYfFUk+P++4dVKZXuutNXT9gPUjVbzOx/tCnl1CwktOEFPEpv9fy64vD00ywUg1SaJgSl5dqA2RGunNSh6hr+pELXYjQ0uQzjMG+Gpknga0EWQEZleOXspw0ClUTrMYuqTooM/8yFfmG5d/p/8wQCCvyIBEQYCSOoOL+li7CBO26GnBvuPxMTvEzQ+0jjOxaEEgc+hOLo1elB+NbxT9Wz5NkJYbkmSUSfk9OZ4vmcvRZbQR9aiqZTeLVB8x6ln/Xzk45zeORcjRQI0fXd5k/dYRLKxKc3DQcXpa3ASzM8VXjx4p3YjcmqMvt+KtKhFL+DbSGxsxjuR6ulk3QJtuM3hnnsRkz58VTZunFsknRr3b0s8pHBYpGw+wLwWJ+IOrk0GBl0MBV705upoi+8xJiqZ7LPvkAe3XRDSV2jPZUyvn5+gzTQ597zTk3zZrpzQ0809UdQRWWkQYF7udozQ4K9+qk34j8Z2IAykgn+ClRmgTdiH87DAIBsZmeSEMjvripBMs5Vkbe3ijnyKuGPREjZ4bgEKrNVl9Y5yNg0=
  file:
    - goxz/maze_darwin_386.zip
    - goxz/maze_darwin_amd64.zip
    - goxz/maze_freebsd_386.tar.gz
    - goxz/maze_freebsd_amd64.tar.gz
    - goxz/maze_linux_386.tar.gz
    - goxz/maze_linux_amd64.tar.gz
    - goxz/maze_netbsd_386.tar.gz
    - goxz/maze_netbsd_amd64.tar.gz
    - goxz/maze_windows_386.zip
    - goxz/maze_windows_amd64.zip
  on:
    repo: itchyny/maze
    tags: true
    all_branches: false
